### ISSUE TITLE
Add method to form example

### ISSUE THREAD

**Issue by intoro** [glassechidna/fwdform2#2]
The method is missing from the example HTML code:
`<form action="<WEB_URL>/user/<public_token>" method="POST">`

One question I get,  "Message is Submitted" but where does the message go? no emails were received and I didn't see anything in postgress. Thanks!

**Comment by Benjamin-Dobell** [comment]
> The method is missing from the example HTML code:

Thanks for pointing that out, fixed in https://github.com/glassechidna/fwdform2/commit/3ac53b4e3297bf7d86a5fe09c451b43f8cd4d9d2

> One question I get, "Message is Submitted" but where does the message go? no emails were received and I didn't see anything in postgress.

Hmm, it might take a _little_ while (i.e. maybe a minute or two) for the email to arrive, _but_ it's been over 10 minutes since you opened this issue. It definitely should have arrived by now! Depending on how aggressive your spam filter is, I suppose it could have been marked as spam.

You can verify the email was sent (and where) by taking a look at Mailgun's logs:

https://app.mailgun.com/app/logs

You won't see anything change in PostgreSQL as the app doesn't bother keeping records as Mailgun takes care of that for us (well, at least short-term logs).

**Comment by intoro** [comment]
I receive the "message submitted" response, but I don't see it in the logs at [](https://app.mailgun.com/app/logs) 
I doubled checked the Mailgun API key and Mailgun domain in the "config Vars" on the Heroku server are correct. Any ideas?

**Comment by intoro** [comment]
I receive the "message submitted" response, but I don't see it in the logs at 
I doubled checked the Mailgun API key and Mailgun domain in the "config Vars" on the Heroku server are correct. Any ideas?

**Comment by Benjamin-Dobell** [comment]
Got to admit, I'm scratching my head a bit on this one.

If you're receiving "Message submitted", that means the Mailgun API responded with a success status. I'm not really sure why it would respond with success and _not_ send the email.

There's still nothing in your [Mailgun logs](https://app.mailgun.com/app/logs)? I think Mailgun give you a special sandbox domain by default. Near the top left corner of that page there's a drop-down list, make sure it has the correct domain selected.

If there's _still_ nothing in the logs. The only thing I can think of is that the Mailgun API returns a success under certain unusual circumstances when it really shouldn't. Perhaps "from_address" is blank 😕

If you're sending an `email` field, fwdform2 will pass this on to Mailgun (as "from_address"). Perhaps double check you're not sending a blank, or otherwise invalid, `email` parameter.

**Comment by intoro** [comment]
Thanks again for your time with this, I am going to go over all the configuration and try again.

**Comment by Benjamin-Dobell** [comment]
@intoro Did you ever manage to sort this out?

**Comment by Benjamin-Dobell** [comment]
I'm going to close this issue, as the original reported issue (incorrect form example in the README) has been addressed. However, feel free to open another issue if you're still having problems.
